### ISSUE TITLE
LSTM - Create a network model

### ISSUE THREAD

**Issue by Shirwarsame** [rdsaliba/notorious-eng#10]
As a dev, I want to develop a Long Short-Term Memory network model so that it calculates the RUL of an asset.

Acceptance
[ ] Implement new model strategy

**Comment by Khal-Shah** [comment]
The LSTM network has been built:
https://github.com/rdsaliba/notorious-eng/tree/10_LSTM_Create_Model/src/main/java/com/cbms/rul/models

However there will be no pull request as external jars are currently needed for this model to run and to integrate DL4J into the project. Simply adding Maven dependency to pom file causes runtime errors. 

There will be another ZenHub issue to address Weka's DL4J package integration.
