### ISSUE TITLE
SonarQube (refactoring + adding unit tests) for Release 1

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#101]
Refactoring task that aims to correct the issues found and identified by SonarQube on the code completed for release 1.

Acceptance Criteria:
~~- [ ] Bug tolerance: 0~~
~~- [ ] Security tolerance: 0~~
~~- [ ] Code smell tolerance: 1-2~~
~~- [ ] Code dupplication tolerance: 3-4%~~
~~- [ ] Code Coverage tolerance: 80%+~~

- [x] Print out the results for quality metrics and code coverage for release 1

**Comment by JayChouteau** [comment]
@rdsaliba we still need to identify the acceptable tolerance for SonarQube code smells, code duplication, and bugs for our code after refactoring (see acceptance criteria of the issue). We could discuss it with the other members, but I think that in a small application like ours, no bugs should be tolerated. As for the code smells and code duplication, our intention should be to remove them all, but maybe the first pass through the different issues noted by SonarQube will allow us to get a better understanding of the situation.

**Comment by JayChouteau** [comment]
@rdsaliba I closed the previous issue for this task and labeled it as a duplicate of this one. This issue is the one we will be using for the SonarQube refactoring task.

**Comment by rdsaliba** [comment]
https://github.com/rdsaliba/notorious-eng/pull/115

**Comment by JayChouteau** [comment]
What is the update on this. Where are we at relative to the acceptance criteria?

**Comment by PaulMicu** [comment]
@JayChouteau As discussed, Jacoco dosent generate the reports so we cant get the code coverage. Waiting for that to be fixed as part of the testing framework issue like we discussed

**Comment by JayChouteau** [comment]
> @JayChouteau As discussed, Jacoco dosent generate the reports so we cant get the code coverage. Waiting for that to be fixed as part of the testing framework issue like we discussed

True we did discuss it. I will add an issue to tackle this situation then because the scope of the system testing framework issue was for automated end-to-end testing and was unrelated to code coverage. I will add it to sprint 5 as high priority.

**Comment by JayChouteau** [comment]
![SonarQube_R1-overall](https://user-images.githubusercontent.com/47158909/104268308-9a2af700-5461-11eb-80d8-0142aeaef8d7.PNG)

Here is the release 1 sonarqube report.

**Comment by JayChouteau** [comment]
![Clover_Release1-coverage](https://user-images.githubusercontent.com/47158909/104268335-aa42d680-5461-11eb-8539-3b60cc078d31.png)

Here is the code coverage report for Release 1 from clover 1

**Comment by JayChouteau** [comment]
The acceptance criteria were changed since fixing release 1 quality issues and improving code coverage for release 1 doesn't make sense at this point (end of sprint 5). The projects have changed a lot and addressing certain issues might be a waste of effort. Instead, a snapshot of the quality metrics and code coverage will be taken at the end of sprint 5 and be corrected during sprint 6.
