### ISSUE TITLE
LSTM - Evaluate the complexity of implementation

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#102]
As a developer, I want to be able to know the effort and complexity required to implement LSTM model.

Acceptance Criteria:
- [x] Confluence doc on the effort needed, complexity, and key points of implementation
- [x] Confluence doc on research on the framework (plugins to be added to our project)

Ex: DeepL for Java

**Comment by Khal-Shah** [comment]
https://notorious-eng.atlassian.net/l/c/cC3X0vMu

**Comment by PaulMicu** [comment]
Good info, i think it you put enough information on the java implementation to be able to start doing
@Khal-Shah  feel free to close this issue if there is no more info you want to add to the doc
