### ISSUE TITLE
Add a system type

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#105]
As a user, I want to be able to include different system types by adding a system type.

Acceptance Criteria:
- [x] A system type can be added through the UI
- [x] Threshold values for the different recommendation boundaries can be chosen
- [x] Assets can be labeled of that new entered type when they are added to the application

*Issue #48 was divided in 2 (#48 is for remove the system type and this one is for adding a system type)

**Comment by jeffbuonamici** [comment]
I finished this issue, however I didn't link this issue when making my commits. Check issue #107 for commits pertaining to this issue.
