### ISSUE TITLE
UI - Create a "System Type" screen

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#106]
Since many requirements ask us to add/remove/edit with system types as well as letting the user establish thresholds for the recommendations of that type, having a screen for system types and their different parameters become necessary.

Acceptance Criteria:
- [x] Create a screen based on the mock-up with the following elements:
- Dashboard/List of system types
- Name of the system type
- Number of associated assets
- Recommendation thresholds
- Button to delete
- Button to edit (renaming + changing the values of the threshold)
- Button to add a system type

**Comment by najimgh** [comment]
Updated Version on Confluence: https://notorious-eng.atlassian.net/l/c/0k27qLQ0
