### ISSUE TITLE
UI - Create a "Add System Type" screen

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#107]
Since we need our users to add system types in the application, we need to have the UI to allow such action.

Acceptance Criteria:
- [x] Create a mock-up for the 'Add System Type' Screen and update the documentation on Confluence
- [x] Create the Screen based on the mock-up. It should contain the following:
- Add a name - field
- Choose the threshold values for the different recommendation boundaries - field

**Comment by jeffbuonamici** [comment]
![Add System Type.png](https://images.zenhubusercontent.com/5f5b96995e1da195741dab57/403de103-4bff-40e2-ac8a-c1c279ebb9a6)

**Comment by jeffbuonamici** [comment]
![image.png](https://images.zenhubusercontent.com/5f5b96995e1da195741dab57/48c6a77a-2e5f-4f01-9f0f-fa372a832284)

**Comment by najimgh** [comment]
UI Mock-up on Confluence: https://notorious-eng.atlassian.net/l/c/H5A0SPPS
