### ISSUE TITLE
Add assets through UI

### ISSUE THREAD

**Issue by Shirwarsame** [rdsaliba/notorious-eng#11]
As a user, I want to add assets to the system using HMI so that it reflects the assets to be monitored.

Refer to UI Prototypes: https://notorious-eng.atlassian.net/l/c/Y5Fr7SZ5

Acceptance criteria:
- [x] Get the data from the UI and add it to the DB
- [x] Associate the new entry with the right dataset (op cond, asset type)
- [ ] unit tests

**Comment by JayChouteau** [comment]
Version 0.6 is currently the latest prototype version:
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/87392587/v0.6

View a list of all versions here:
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/24379414/UI+Prototypes
