### ISSUE TITLE
UI_Mock-up - Create a "Raw Data" Screen Mock-up

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#110]
One of the user stories requires us to display the raw data for a specific asset. The first step is having a mock-up for that UI.
Acceptance Criteria:
- [x] Create a mock-up for the "Raw Data" screen and add it to the documentation on Confluence
- [x] The screen should be accessible from the "System information" screen

**Comment by rdsaliba** [comment]
![System – 1.png](https://images.zenhubusercontent.com/5f5b90e88d247ac7ad2cf5c0/06aaf14e-e4b5-4203-b4c2-d0f7edd7c3f3)

**Comment by rdsaliba** [comment]
![System – 2 Raw Data Tab.png](https://images.zenhubusercontent.com/5f5b90e88d247ac7ad2cf5c0/19da1d5c-22a9-4377-bab2-c8ed8a43fd3a)

**Comment by rdsaliba** [comment]
Please let me know what you think of the design so that we can move forward with the implementation on JavaFX.
@jeffbuonamici @JayChouteau @PaulMicu

**Comment by JayChouteau** [comment]
The mock-up looks good for raw data. We talked about it at the last meeting on thursday 26-11-2020. Everyone agreed with it and with the tab idea.

**Comment by najimgh** [comment]
UI mock-up on Confluence: https://notorious-eng.atlassian.net/l/c/1Mhse1ve
