### ISSUE TITLE
UI - Create a "Raw Data" Screen

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#120]
One of the user stories requires us to display the raw data for a specific asset. This screen needs to be created first in the UI,

Acceptance Criteria:
- [x] Mock-up update in Confluence (link to be provided in this issue)
- [x]  Create a screen based on the mock-up. Make sure all elements are present.
- [x]  The screen should be accessible from the "System information" screen.
- [ ] Unit tests

**Comment by jeffbuonamici** [comment]
![image.png](https://images.zenhubusercontent.com/5f5b96995e1da195741dab57/506290c6-9272-49af-9acc-46ccce4faba1)

**Comment by najimgh** [comment]
UI Mock-up on Confluence: https://notorious-eng.atlassian.net/l/c/A8AHExxr
