### ISSUE TITLE
UI/Mock-up - Create a "System Type" screen Mock-up

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#121]
Since many requirements ask us to add/remove/edit with system types as well as letting the user establish thresholds for the recommendations of that type, having a screen for system types and their different parameters become necessary.

Acceptance Criteria:

- [x]  Mock-up for the system type view (add to the documentation):
- [x] Dashboard/List of system types
- [x] Name of the system type
- [x] Number of associated assets
- [x] Recommendation thresholds
- [x] Button to delete
- [x] Button to edit (renaming + changing the values of the threshold)
- [x] Button to add a system type

**Comment by najimgh** [comment]
All criteria are taken into account and mock-ups have been posted to confluence.
Mock-up link: https://notorious-eng.atlassian.net/l/c/L2Ydizf3

**Comment by najimgh** [comment]
Updated Version on Confluence: https://notorious-eng.atlassian.net/l/c/0k27qLQ0
