### ISSUE TITLE
UI/Mock-up - Create a "Add System Type" screen Mock-up

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#122]
Since we need our users to add system types in the application, we need to have the UI to allow such action.

Acceptance Criteria:
- [x]  Create a mock-up for the 'Add System Type' Screen and update the documentation on Confluence
- [x] Add a name - field
- [x] Choose the threshold values for the different recommendation boundaries - field

**Comment by jeffbuonamici** [comment]
![Add System Type.png](https://images.zenhubusercontent.com/5f5b96995e1da195741dab57/cd782c07-f819-40f6-96c5-bed5963de9f7)

**Comment by jeffbuonamici** [comment]
I just need some clarity on what these threshold values are. I'll be discussing that at today's meeting.

**Comment by jeffbuonamici** [comment]
![image.png](https://images.zenhubusercontent.com/5f5b96995e1da195741dab57/e11e3084-937e-4c15-add0-f72c37f217d2)

**Comment by najimgh** [comment]
UI Mock-up on Confluence: https://notorious-eng.atlassian.net/l/c/H5A0SPPS
