### ISSUE TITLE
Improve linear regression model performance

### ISSUE THREAD

**Issue by Shirwarsame** [rdsaliba/notorious-eng#13]
As a dev, I want to improve the calculation error of the RUL using linear regression so that the accuracy lies between 5 and 10%. 

Acceptance Criteria:
- [ ] Rul calculating Accuracy between 5-10%

**Comment by TalalBazerbachi** [comment]
- With the Dataset that we have, getting the Root Mean Squared Error to the acceptance criteria mentioned is unreasonable.
