### ISSUE TITLE
Refactoring - UI

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#134]
This is a refactoring issue regarding the UI:

### 0) General
- [x] Provide dummy data for several assets regarding their information (attributes such as location, site, description, etc) so that the UI is filled out and gives a better representation of a real setting.
- [x] Left-side panel displays the "Systems" title fully - Check with Mac users (Roy, Talal, Najim)
- [x] Add an exit button at the bottom of the left side panel
- [x] Rename top bar/remove it if possible

### 1) Systems - Thumbnails view
- [x] Information to display for each asset: asset SN, asset type name, location, RUL model, RUL value, recommendation
~- [ ] Use color-coding to represent the recommendation~ we dont have recommendation yet
- [x] Re-size the thumbnails to reduce the blank space on each asset thumbnail

### 2) Systems - List view
- [x] Information to display for each asset: asset SN, asset type name, location, RUL model, RUL value, recommendation + other useful information including description to fill the blank spaces
- [x] separate the RUL model and value into 2 different columns

### 3) System info view
- [x] Title should be : _Name Asset Type_ - _Asset SN_
- [x] For sensor graphs: The name of the sensor should be on top of the graph
- [x] Graphs should show the last 5 cycles instead of the first 5 cycles
- [x] Graphs scaling should be re-sized to show variation
~- [ ] A list view should be created for the sensors as well~
~- [ ] Confirm dialog for deletion should only show a question~
~- [ ] Confirm dialog for deletion should have a "Yes" or "No" answer~
~- [ ] Confirm dialog for deletion should fit better the style of the app~

### 4) Add system view
- [x] Make textboxes thicker for touchpads
- [x] For the system description textbox, the text should automatically return to the next line once he reaches the limit of the textbox
- [x] For the system type name, this should be a dropdown showing the existing system type names.

**Comment by PaulMicu** [comment]
script v4.03 will populate the asset tables with dummy data

**Comment by JayChouteau** [comment]
The naming for all buttons was changed to be more consistent. It would be good to pull from this branch (origin) before you keep working on it @jeffbuonamici. The Add system modifications are all done except for 1 that is waiting for the merge of pull request #149

**Comment by JayChouteau** [comment]
Branch #135  was merged into this one since it is a branch that was used for a refactoring issue that has an impact on the UI.

**Comment by PaulMicu** [comment]
the pop up dialog box will be done as a separate issue

**Comment by PaulMicu** [comment]
the list view for the sensor will also be a separate issue as it's an improvement not a refactoring activity
