### ISSUE TITLE
Set up a Docker Container

### ISSUE THREAD

**Issue by Shirwarsame** [rdsaliba/notorious-eng#14]
As a developer, I want to set up a Docker Container in order to make the application portable

**Comment by JayChouteau** [comment]
Docker container configurations set-up in the POM file in the <plugins>. What is missing is running an actual container from the project. The issue related to TensorFlow needs to be resolved first and then run it. See on Docker_dependency branch.

**Comment by rdsaliba** [comment]
What is the status of this issue?
Please leave an estimated time to completion.. this should be done by now.

**Comment by jeffbuonamici** [comment]
After speaking to the PO, this has been changed to low priority. Thus, it will be pushed back to later in the development cycle.
