### ISSUE TITLE
Populate the "System Type List" screen

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#156]
Since many requirements ask us to add/remove/edit with system types as well as letting the user establish thresholds for the recommendations of that type, having a screen for system types and their different parameters become necessary.

Acceptance Criteria:
- [x]  Add a side menu button to link to this page called "System types" with a different icon than the one for "System"
- [x]  List of system types
- [x]  Name of the system type
- [x]  Number of associated assets
- [x]  Recommendation thresholds
- [x]  Button to add a system type (links to proper page)

**Comment by PaulMicu** [comment]
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/351109149/v1.3
