### ISSUE TITLE
[Spike] Research - RUL models

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#159]
Research issue to explore and find new RUL models that could be used in our application in addition to LSTM and Linear Regression.

Acceptance Criteria:
- [x] Documentation on Confluence about the research and showing an ordered list of the different models based on their suitability for our client (the type of data analyzed), their performance, and ease of use.

Document between 5-7 models that could be implemented in our project

**Comment by Khal-Shah** [comment]
https://notorious-eng.atlassian.net/l/c/YLDX018N
