### ISSUE TITLE
Sorting Assets by Maintenance recommendation

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#161]
As a user, I want to be able to sort the assets by maintenance recommendation.

Acceptance Criteria:
- [ ] Update documentation for mock-ups on Confluence (link to be provided in the issue)
- [ ] Sorting button/option on the systems thumbnails view
- [ ] The assets in the thumbnail view can be sorted by maintenance recommendation (ascending or descending criticality)
- [ ] Unit tests

**Comment by PaulMicu** [comment]
This issue has been moved to Review but i dont see any PR associated with this
