### ISSUE TITLE
System Testing - Assets

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#162]
This system testing batch targets the user stories concerning the displaying, consulting, or editing of the assets. A batch means that different system test scenarios need to be developed for the asset-related user stories.

Acceptance Criteria:
- [ ] Documentation on Confluence for the system test sections, cases and scenarios

Develop functioning system tests scenarios and implementing them (automated end-to-end tests) for the following user stories/issues:
- [ ] Display asset information (thumbnails)
- [ ] Display asset information (list view)
- [ ] Scroll through the thumbnails view
- [ ] Scroll through the list view
- [ ] Add Asset
- [ ] Remove Asset

The system tests are implemented using the testfx framework set up in the e2e folder.

**Comment by jeffbuonamici** [comment]
Tests for our JavaFXUserInterface Package.
![image.png](https://images.zenhubusercontent.com/5f5b96995e1da195741dab57/2b81d6cd-04b3-438e-b926-1b290d49c830)

![image.png](https://images.zenhubusercontent.com/5f5b96995e1da195741dab57/e81b1a9f-0186-45e2-8e3b-cd2817bf82c4)
