### ISSUE TITLE
Virtualization of Data - Assets

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#163]
As a user, I want to be able to use the application with fluid and performant UI.

Acceptance Criteria:
- [ ] Only have a sublist of assets displayed on the assets thumbnails view
- [ ] Increase the number of assets displayed once you scroll down through the page
- [ ] The increase of the sublist should be done incrementally according to the scrolling
- [ ] Filters and Order By should still work properly and consider all assets
- [ ] Unit Tests
- [ ] Code Convention Clean-up

**Comment by PaulMicu** [comment]
Solution proposed to use caching instead of virtualization, i asked the team members who had difficulties in the past to try out the changes on the branch and see if the implemented solution is sufficient.

**Comment by JayChouteau** [comment]
@PaulMicu It runs smoother on my end. Maybe try with the images to see if it still works just as smoothly.
