### ISSUE TITLE
General page Asset type info view

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#167]
As a user, I would like to see information about a specific asset type.

We need a UI page to view information related to a specific asset type. This view should be accessible from the "asset type list" view.

Acceptance Criteria:
- [x] Create the mockup and publish it on Confluence (link to be inserted in this issue)

Before moving on with building the UI, the mockup should be approved by the whole team.
Create a screen based on the mock-up with the following elements:
- [x] In a tab format with this being the only element for now
- [x] Asset type name
- [x] Asset type description
- [x] Asset type threshold names with values (to be filled with live data after sprint 6)
- [x] Image of the asset type
- [x] The associated model
- [x] Edit Button
- [x] Remove Button

**Comment by najimgh** [comment]
Mock-up posted on Confluence: https://notorious-eng.atlassian.net/l/c/dPkEDwd7

**Comment by najimgh** [comment]
Along with the System Type info View, I have added a System Type Edit view
