### ISSUE TITLE
Setup JAVA Environment

### ISSUE THREAD

**Issue by Shirwarsame** [rdsaliba/notorious-eng#17]
As a developer, I want to setup my JAVA environment

 - [ ] Install JAVA 11
 - [ ] Install Maven to manage dependencies
 - [ ] Install Docker 
 - [ ] Install SonarQube

*On your machine

- [x] @JayChouteau 
- [x] @jeffbuonamici 
- [x] @Khal-Shah 
- [x] @najimgh  
- [x] @PaulMicu  
- [x] @Shirwarsame 
- [x] @rdsaliba 
- [x] @t98b

**Comment by rdsaliba** [comment]
[ ] Install JAVA 11
[ ] Install Maven to manage dependencies
[ ] Install Docker 
[ ] Configure SonarQube

*On your machine

**Comment by JayChouteau** [comment]
Hey guys, anyone here with a windows? IT seems you can only install docker on windows with a Pro/enterprise or a Home version of windows,

**Comment by PaulMicu** [comment]
@JayChouteau  What version of Windows do you have?
