### ISSUE TITLE
Doc R2 - Architecture

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#172]
Acceptance Criteria:
- [x] Release 2 documentation for the Architecture section

Make sure all sections are updated:
- [x] Overview (Roy)
- [x] Domain model (Jeremie/Talal)
- [x] Component Diagram (Talal)
- [x] ER Diagram (Jeremie)
- [x] Class Diagram (Najim/Shirwa)
- [x] Design patterns (Najim)
- [x] External libraries (Jeremie)
- [x] Experimental design (Khaled)

The release 2 document, as well as the release 2 template, are in the team's drive.

Feedback from release 1:
The class diagram does not include dependencies yet between the classes. I see you introduced some abstractions. When you will proceed more with the implementation, you will have more concrete ideas about how to improve and finalize the design. All other diagrams are well done.
Excellent work on the research related to machine learning.

**Comment by JayChouteau** [comment]
ER diagram section is done.

**Comment by najimgh** [comment]
Class Diagrams Done

**Comment by JayChouteau** [comment]
I am not sure what to add in external libraries. Did we use any other external libraries? SonarQube, OpenClover and TestFx are all tools that are discussed in their respective section. I am not sure as to what to add other than weka, JDBC and JavaFX.

**Comment by JayChouteau** [comment]
Components diagrams are reviewed. Done.

**Comment by JayChouteau** [comment]
@t98b Domain model looks good. But we need to update the text and the link to Confluence. Could you do it please?

**Comment by najimgh** [comment]
Design Patterns done

**Comment by JayChouteau** [comment]
Reviewed.
