### ISSUE TITLE
Doc R2 - Defect Tracking report

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#175]
Acceptance Criteria:
- [x] Release 2 documentation for the Bug section

The release 2 document, as well as the release 2 template, are in the team's drive.

Feedback from release 1:
Only 1 bug report. This was a bug reported by SonarQube.

**Comment by JayChouteau** [comment]
@najimgh -> review

**Comment by najimgh** [comment]
Documentation is good. I have added some comments on issues where the solution for a bug was not mentioned.
