### ISSUE TITLE
Release 2 Presentation

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#179]
Release 2 presentation. Acceptance criteria:
1) 30 min presentation with the following contents:
- [x] Release retrospective (a brief overview of the completed user stories, what problems you faced, how did you overcome these problems, what are you still struggling with, issues with the product owner)
- [x] Architecture (Explain how you evolved your design, especially for the design patterns you introduced in the previous release, discuss any new design decisions you made)
- [x] Testing report (number of unit tests, test code coverage, system/UI automated tests, signed-off acceptance tests)
- [x] Quality assurance report (show the evolution of software metrics, technical debt, security vulnerabilities, and code convention violations throughout the sprints of the second release, what actions did you take (or you plan to take) to address these issues)
- [x] Usability/Performance report (Discuss the metrics and tools you used, the characteristics of the user group that participated in testing (or performance load characteristics), show the test results, and discuss the actions you plan to take to improve usability/performance)

2) Video recording - All Features
- [x] demonstrating all features you implemented in the second release (screen capture with a voice-over explaining the features)

3) Video recording - 1 Feature + code
- [x] going through the code of one feature you implemented. You will select the feature you believe was the most challenging, and explain the relevant source code, key design decisions related to the feature, and the relevant test code (including code related to usability/performance testing)

**Comment by rdsaliba** [comment]
Work in progress:
https://docs.google.com/presentation/d/19lGKqx9BD8Tr4blpgu0JfLPO-60By1D_LXYW0umzdQI/edit#slide=id.gb9ae7e8d9f_0_69
