### ISSUE TITLE
Performance - Memory Leak 

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#180]
**Describe the bug**
The application becomes non-responsive. 
Trace: Exception in thread "JavaFX Application Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached

**To Reproduce**
1. Launch the application
2. Click on "List" view
3. Select any System to view its information
4. Click back on "Systems" on the side bar
5. See error

**Expected behavior**
Clicking on the "Systems" button on the side bar should bring me back to "List" view

**Screenshots**
![Screen Shot 2021-01-13 at 3 46 09 PM](https://user-images.githubusercontent.com/17152773/104508603-7b8a4480-55b6-11eb-914d-a466f8bef309.png)

**Desktop (please complete the following information):**
 - OS: **macOS Big Sur**
 - Branch: Develop

**Additional context**

**Comment by PaulMicu** [comment]
i cant replicate the issue, my guess is that i have allocated more resources to inteliji than you and thats why you're getting an out of memory exception and i'm not. It looks like the issue is from all the asynchronous threads that get started to update the UI with live data.

**Comment by najimgh** [comment]
Solution: https://github.com/rdsaliba/notorious-eng/pull/184

Project restructured into modules.
To run a module, make sure that the other modules that are a dependency have been compiled and are up to date with the latest changes
