### ISSUE TITLE
Bug: List view empty cell

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#186]
**Describe the bug**
In the list view, trying to access an empty cell which does not hold a reference to any asset will direct to the template "System view". In the system logs, an error will be triggered. See attached pictures.

**To Reproduce**
1. Go to 'List'
2. Click on an empty cell
3. See template for System view
4. See error in system logs

**Expected behavior**
Clicking on an empty cell should not redirect to another view. Expected behaviour is no change at all.

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/17152773/104967101-8c6cf880-59b0-11eb-96fb-9df2bf1a2c8f.png)
![image](https://user-images.githubusercontent.com/17152773/104967102-8d058f00-59b0-11eb-8767-11c20bd1f7cb.png)

**Comment by najimgh** [comment]
**Note:** The same bug also happens for the **System type List** page. That will need to be fixed as well.

**Comment by najimgh** [comment]
Solution: Added a null or empty check on the event listener
