### ISSUE TITLE
Create Use Cases

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#19]
As a dev, I want to create the use cases so that we can visualize the functional requirements of the system.

The number of tables on the page do not represent the expected use cases to produce. Please add accordingly.
Use cases are requirements; primarily they are functional requirements that indicate what the system will do. They define a promise or contract of how a system will behave.

https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/6586390/Use+Case+Definition

**Comment by rdsaliba** [comment]
Hi @najimgh 
UC03, UC04, UC05 are out of the scope of the project. In no way we are adding, removing an RUL algorithm. Please consider reviewing the requirements as outlined in the CBM file on the drive. Also needs to be more exhaustive.

**Comment by najimgh** [comment]
Need to talk about system instances and how to handle them.
Need to have a prototype for adding system instances.
Need to have a prototype for adding RUL Models.
