### ISSUE TITLE
Unit testing - Raising up the coverage

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#194]
This issue is meant to raise the code coverage of our project. Clover is the tool being used to assess code coverage and unit testing.

Acceptance Criteria:
- [ ] 70% of code coverage with unit tests

To run Clover, please check the following documentation:
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/295141377/Unit+testing

**Comment by jeffbuonamici** [comment]
Tests for the Server package

![image.png](https://images.zenhubusercontent.com/5f5b96995e1da195741dab57/bbd3e55e-93cd-427c-88b0-f40f80f75d64)

![image.png](https://images.zenhubusercontent.com/5f5b96995e1da195741dab57/c5db0b63-f042-405a-8e85-519bcb3bba70)

**Comment by jeffbuonamici** [comment]
Tests for the Server package.

![image.png](https://images.zenhubusercontent.com/5f5b96995e1da195741dab57/ceceb9bc-2c8d-4cb6-8b2e-b815de35bf13)

![image.png](https://images.zenhubusercontent.com/5f5b96995e1da195741dab57/12f49d6b-30be-4255-a2e7-a33b7a658780)

**Comment by PaulMicu** [comment]
this shows the coverage using the server unit tests
![image.png](https://images.zenhubusercontent.com/5f5b934c43e9ce0f4a16ecde/83f51ee0-3479-4da2-9fed-9d2b03cdb55d)
