### ISSUE TITLE
 F15 Display Raw Data

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#201]
F15 - The system shall display a selected system raw data

Acceptance criteria:
- [x] On the system info view, there is a tab called "RAW DATA"
- [x] The Raw Data tab view can be accessed when you click on the tab
- [x] Raw data information corresponding to this specific asset is displayed
- [x] Raw data information contains: the list of measurements for that specific asset, associated with the time cycle of those measurements and the identified by the attribute (sensor) that collected the measurement
- [x] The latest raw data information is displayed at the top of the list

**Comment by jfstamand** [comment]
On the system info view, there is a tab called "RAW DATA" -- OK
 The Raw Data tab view can be accessed when you click on the tab -- OK
 Raw data information corresponding to this specific asset is displayed -- OK
 Raw data information contains: the list of measurements for that specific asset, associated with the time cycle of those measurements and the identified by the attribute (sensor) that collected the measurement -- OK
 The latest raw data information is displayed at the top of the list -- OK

Approved
