### ISSUE TITLE
F-13 RUL Ascending/Descending

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#202]
F13 - The system shall display a monitored system in RUL order (lowest RUL first)

Acceptance criteria:
- [x] There is an option that lets the user order the asset by RUL value  on the systems thumbnail view
- [x] When that option is checked to ascending, the assets are displayed by Ascending RUL value on the systems thumbnail view
- [x] When that option is checked to descending, the assets are displayed by Descending RUL value on the systems thumbnail view
- [x] In the systems list view, the user can click on the column header of the RUL value to order by descending or ascending value
- [x] Depending on which option is chosen in the systems list view, the list of assets will be ordered by corresponding ascending or descending value

**Comment by jfstamand** [comment]
There is an option that lets the user order the asset by RUL value on the systems thumbnail view -- OK
 When that option is checked to ascending, the assets are displayed by Ascending RUL value on the systems thumbnail view -- OK
 When that option is checked to descending, the assets are displayed by Descending RUL value on the systems thumbnail view -- OK
 In the systems list view, the user can click on the column header of the RUL value to order by descending or ascending value -- OK
 Depending on which option is chosen in the systems list view, the list of assets will be ordered by corresponding ascending or descending value -- OK

Approved
