### ISSUE TITLE
 F5 - User Recommendations

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#203]
F5 - The system shall suggest maintenance actions/recommendations to the user.

Acceptance Criteria:
- [x] The maintenance recommendations are displayed on the systems thumbnail view
- [x] The maintenance recommendations are displayed on the system list view
- [x] The maintenance recommendation is displayed on the system info view
- [x] The maintenance recommendations are based on the threshold boundary values
- [x] The threshold boundary values are set for a specific asset type
- [x] The threshold boundary values are displayed on the system type info view
- [x] The threshold boundary values are editable on the system type info view and can be saved

**Comment by jfstamand** [comment]
The maintenance recommendations are displayed on the systems thumbnail view -- OK
 The maintenance recommendations are displayed on the system list view -- OK
 The maintenance recommendation is displayed on the system info view -- OK
 The maintenance recommendations are based on the threshold boundary values -- OK
 The threshold boundary values are set for a specific asset type -- OK
 The threshold boundary values are displayed on the system type info view -- OK 
 The threshold boundary values are editable on the system type info view and can be saved --OK

Approved
