### ISSUE TITLE
S1 - The System shall have a plugin-based architecture to add or remove a RUL model

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#204]
~~F6 - The system shall provide the ability to add and remove a RUL model.~~
(Changed after discussion with PO)

S1 - The System shall have a plugin-based architecture to add or remove a RUL model

Acceptance Criteria:
- [x] To add a model, the only needed action is to add an implementation file of the new model at the proper location (server module -> rul -> models package) and adding it to the switch case instantiation of the models in the model controller file
- [x] To "remove" or archive a model, the only needed action is to changed the archived attribute to 1 instead to 0 in the model table

**Comment by rdsaliba** [comment]
The following issue is to be redefined as a System Requirement, as discussed with the product owner.

Previous scope:
Add/Remove RUL model from the user interface

New scope:
Add/Remove RUL model using strategy pattern in the backend is enough to satisfy the requirement. The code responsible for this functionality has been demonstrated during the meeting.

**Comment by jfstamand** [comment]
Agreed with rdsaliba's comment

**Comment by jfstamand** [comment]
Approved
