### ISSUE TITLE
F11 Add/Remove System Type

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#206]
F11 - The system shall provide the ability to add and remove a system type.

Acceptance Criteria:
1) Delete
- [x] On the system type information view, there is a button that allows you to delete an asset type
- [x] Clicking on the delete button pops up a confirm dialog box
- [x] Confirming the delete of the asset type takes you back to the system type list view
- [x] After confirmation, once the system type list view is displayed, the deleted system type does not appear in the list
- [x] All assets of that deleted asset type have also been deleted from the application
- [x] All assets of that deleted asset type are not displayed in the system thumbnail view
- [x] All assets of that asset deleted type are not displayed in the system list view

2) Add
- [x] On the system type list view, there is a button to add a new system type
- [x] After clicking the add button, the user is directed to the Add System Type view
- [x] The user can input data/information for the following fields: name, description, and all threshold values
- [x] On the add system Type view, there is a button to add/save the new asset type
- [x] When clicked, the system type list view is displayed and the new added asset is displayed in the list.
- [x] All the information entered for that added asset type is correctly displayed

**Comment by jfstamand** [comment]
1) Delete

 On the system type information view, there is a button that allows you to delete an asset type -- OK
 Clicking on the delete button pops up a confirm dialog box -- OK
 Confirming the delete of the asset type takes you back to the system type list view -- OK
 After confirmation, once the system type list view is displayed, the deleted system type does not appear in the list -- OK
 All assets of that deleted asset type have also been deleted from the application -- OK
 All assets of that deleted asset type are not displayed in the system thumbnail view -- OK
 All assets of that asset deleted type are not displayed in the system list view-- OK

2) Add

 On the system type list view, there is a button to add a new system type -- OK
 After clicking the add button, the user is directed to the Add System Type view -- OK
 The user can input data/information for the following fields: name, description, and all threshold values -- OK
 On the add system Type view, there is a button to add/save the new asset type -- OK
 When clicked, the system type list view is displayed and the new added asset is displayed in the list. -- OK
 All the information entered for that added asset type is correctly displayed -- OK

Approved
