### ISSUE TITLE
F12 - Associate System Type to RUL Model 

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#207]
F12 - The system shall provide the ability to associate a system type with RUL model

Acceptance Criteria:
Selecting a model and clicking on "Save" saves the association in the database

When saving an association
- [x] The trained model used for calculating RUL is updated for that asset type (in the database)
- [x] The trained model is set to be retrained (in the database)
- [x] All assets are set to be updated (in the database)
- [x] on the information tab of the modified type, the associated RUL model field has been updated
- [x] on the model tab of the modified asset type, the selected model thumbnail has been updated
- [x] on an asset's information page, the RUL model field has been updated (the asset has to be of the asset type modified)
- [x] the assets of that asset type will have their RUL calculations and estimations modified

**Comment by jfstamand** [comment]
Approved
