### ISSUE TITLE
 F16 Display System Information

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#209]
F16 - The system shall display a selected system information

Acceptance Criteria:
Selecting an asset will provide the following information:
- [x] name
- [x] description
- [x] location
- [x] manufacturer
- [x] category
- [x] site
- [x] serial number
- [x] asset type
- [x] recommendation
- [x] all asset's attribute measurements

**Comment by jfstamand** [comment]
Approved
