### ISSUE TITLE
Develop personas

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#21]
As a developer, I need to develop personas so that we have a user-centered design

**Comment by Khal-Shah** [comment]
- [x] Develop at least 2 personas for use cases of the software.
- [x] Include goals and challenges.
- [x] Write a scenario for each.

**Comment by Khal-Shah** [comment]
First persona: 
https://notorious-eng.atlassian.net/l/c/fQu5GTBS

**Comment by Khal-Shah** [comment]
Second Persona:
https://notorious-eng.atlassian.net/l/c/H159Qbi4

**Comment by rdsaliba** [comment]
What would differentiate the 2 personas in terms of functional needs?
- usability goals?
- exprience goals?

**Comment by rdsaliba** [comment]
What is the current status of this issue? @Khal-Shah

**Comment by Khal-Shah** [comment]
Added a 3rd persona instead of just editing the 2nd one. 

We probably won't use the 2nd one but left it there anyway incase we do.

https://notorious-eng.atlassian.net/l/c/iJjzrWfh

I think we can close the issue for now unless there are any adjustments to be made.
