### ISSUE TITLE
 F17 Add/Remove a System.

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#210]
F17 - The system shall provide the ability to add or remove a system.

Acceptance criteria:
- [x] On the system thumbnail view, there is a button to add a system
- [x] When clicked, the Add System view is displayed
- [x] The Add System view allows the user to enter data/information about the new asset
- [x] The information that can be entered about the new asset is the following: name, description, location, site, manufacturer, category, and serial number.
- [x] On the Add System View, there a dropdown that allows the user to associate the asset with a specific asset type.
- [x] On the Add System view, there is a button that allows saving the added asset.
- [x] Once saved, the user is taken back to the system thumbnail or list view depending on which he was on when he click the add system button
- [x] After confirmation of the added asset, this new asset is displayed in both the systems thumbnail and list views

**Comment by jfstamand** [comment]
On the system thumbnail view, there is a button to add a system --OK
 When clicked, the Add System view is displayed --OK
 The Add System view allows the user to enter data/information about the new asset --OK
 The information that can be entered about the new asset is the following: name, description, location, site, manufacturer, category, and serial number. --OK
 On the Add System View, there a dropdown that allows the user to associate the asset with a specific asset type. --OK
 On the Add System view, there is a button that allows saving the added asset. --OK
 Once saved, the user is taken back to the system thumbnail or list view depending on which he was on when he click the add system button --OK
 After confirmation of the added asset, this new asset is displayed in both the systems thumbnail and list views --OK

Approved
