### ISSUE TITLE
(E1) UI Enhancements - Suggestions Issue

### ISSUE THREAD

**Issue by Shirwarsame** [rdsaliba/notorious-eng#217]
As a user, I want a cleaner and more user-friendly UI interface.

This issue serves to collect every member's ideas and suggestions for improving the UI.

**Comment by rdsaliba** [comment]
Please leave your comments here! @jeffbuonamici @JayChouteau @PaulMicu @t98b @Khal-Shah @najimgh @Shirwarsame

**Comment by jeffbuonamici** [comment]
I’d like to see the SystemInfo page have the System details split into tiles, that groups related information together.

For Systems page, each tile should only include the title, image, rul value and status. Anything more would be too cluttered

Add more color to the pages, but nothing too flashy

**Comment by Shirwarsame** [comment]
Color palette change, make the UI more colorful and bright.

**Comment by PaulMicu** [comment]
I would like to see the thumbnail and list view for asset to handle recommendation with a visual feedback on the background of the thumbnail/list fx element. Going from green to red as indicated by the current recommendation of the asset.  the colour should be very subtle but deep enough to recognize it. Something like this ![image.png](https://images.zenhubusercontent.com/5f5b934c43e9ce0f4a16ecde/2b11618b-3bfe-4898-a203-4ca0e9dfd7fa)

**Comment by najimgh** [comment]
- I'd like for the user to be able to choose any image of his choice when adding an Asset Type. This solves the problem of dynamically displaying a certain image for an Asset Type.
- The image should also be displayed in a better position than it currently is.

**Comment by Khal-Shah** [comment]
P.O mentioned he wants transitions and animations, so some sort of "sliding" transition effect when going to another page would be great. As for animation, we should have a "loading" animation any time a model is being trained (we could call it training instead of loading).

**Comment by JayChouteau** [comment]
Here are my comments:
- In general, it would be great if the disposition, styling and coloring from 1 file to the other was more consistent. This concerns how buttons look like and how are they placed in different UI screens, our font, etc.
- Having more clarity and definition/separation between elements. Right now, all our UI elements seem to be on the same level, there is no order of importance between the texts based on the color or the bolding. Also, with our current UI visual, it makes it hard to define a difference between elements as they are close to one another and there isn't a sens of separation. Basically, more levels of importance given by color and styling as well as more element defining.
- Tabs should be highlighted when selected to provide more clarity on which tab you are currently on. The unselected tabs could be grayed out or put in the back.
![image](https://user-images.githubusercontent.com/47158909/107272942-6faa6a80-6a1c-11eb-911c-30fe1238797f.png)

**Comment by JayChouteau** [comment]
@Khal-Shah Thanks for reminding us for the loading screen. This should be added as an issue. Not sure if it should be part of the UI feature Epic or part of this Enhancement epic
