### ISSUE TITLE
Doc R3 - Defect Tracking report

### ISSUE THREAD

**Issue by Shirwarsame** [rdsaliba/notorious-eng#219]
Acceptance Criteria:
- [ ] Release 3 documentation for the Bug section

The release 3 document, as well as the release 3 template, are in the team's drive.

Feedback from release 2:
7 bugs reported and fixed. Only in Sprint 6 you started using a common bug report template, and added replication steps, screenshots, etc.

**Comment by JayChouteau** [comment]
@t98b The links provided did not follow the template, so I changed it. Done.
