### ISSUE TITLE
Integrate SonarQube

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#22]
As a developer, I want to integrate SonarQube so we can measure and analyse the source code quality

Subtask of #31

**Comment by rdsaliba** [comment]
Jacoco Java Code Coverage

**Comment by PaulMicu** [comment]
added maven dependency in #34

**Comment by PaulMicu** [comment]
Docker already has a SonarQube container all set up, we will be using sonarqube in docker for our project : https://hub.docker.com/_/sonarqube/
