### ISSUE TITLE
Design the UI Prototypes

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#23]
As a developer, I need to design the UI prototypes of the system so we have a representation of the final product

**Comment by PaulMicu** [comment]
V0.1 done by Jeff: https://notorious-eng.atlassian.net/l/c/M1hrFEtW

**Comment by jeffbuonamici** [comment]
v0.2 is done: https://notorious-eng.atlassian.net/l/c/Vuh0Z1oq

Feedback would be appreciated! If anyone wants to help with UI, that's fine as well.

**Comment by rdsaliba** [comment]
Is that the skeleton of the UI?
Missing details, views and the flow.

- System informations
- Graphs
- Sensors
- Assets Health Index (maybe?)

Please see prototypes in the document proposal with expectations from PO.

**Comment by jeffbuonamici** [comment]
Yes this is more of a skeleton of the UI showing the systems. Each thumbnail you see would be a system and show critical information about the system. Once you click on the thumbnail, you would get a more detailed view about the system showing the sensors.

One thing I haven't touched on yet is the "Parameters View" in our proposal document. I'm not clear on what that is supposed to be.

Here is a link to a new version that hopefully makes things more understandable:
https://notorious-eng.atlassian.net/l/c/TFHk1kdJ

**Comment by jeffbuonamici** [comment]
Added a tablet version based on prototype v0.3.

v0.31
https://notorious-eng.atlassian.net/l/c/1f0unnMk

**Comment by jeffbuonamici** [comment]
Version v0.4:
https://notorious-eng.atlassian.net/l/c/SteCf3qq

**Comment by JayChouteau** [comment]
@jeffbuonamici The comments/list has been posted on version v0.31

**Comment by jeffbuonamici** [comment]
The following is a link to ALL prototype versions:
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/24379414/UI+Prototypes
