### ISSUE TITLE
(E1) UI Enhancements - UI Mock-ups

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#236]
As a user, I want a cleaner and more user-friendly UI interface.

Acceptance Criteria:
- [x] Add the missing UI Mock-ups on Confluence
- [x] Update the UI Mock-ups to fit how they will look like after the UI Enhancements (including UI suggestions)

**Comment by jeffbuonamici** [comment]
We are revamping the UI using feedback from the team. Click the link to see the feedback:
https://app.zenhub.com/workspaces/notorious-eng-5f5b91b10156a900162c5640/issues/rdsaliba/notorious-eng/217
