### ISSUE TITLE
General Enhancements - Code Convention Refactoring

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#238]
As a developer, I want to have consistent, clear, and comprehensive code that follows a structure.

Acceptance Criteria:

1) Establish and enforce consistent naming between the documentation, UI and Code. Examples:
- [x] boundaries -> thresholds
- [x] Systems -> Assets
- [x] System Types -> Asset Types
- [x] Sensor -> Attribute

2) Establish and enforce consistent naming and conventions for the use of String constants. Team Consensus was:
- [x] If constant is used in multiple files, get all the string constants in the text constants file
- [x] If constant is used in 1 file, get the string constant at the top of the file
- [x] If constant is a display text Constant, put it in the text constants file

3)  Establish and enforce consistent comment convention. Team consensus:
- [x] Comments at the beginning of a file as it seems documentation asks for it (quick summary of the class, remove versions).
- [x] Javadoc comments before each method that explains what it does. (Not stating the obvious, but giving context or needed explanation).

**Comment by najimgh** [comment]
Note: Investigate how to apply code convention for the whole project.
- What needs to be changed to the code convention for the project?

**Comment by najimgh** [comment]
I need all of you to check some functions and add header comments if you are the one who created/modified it.
To do that, you’ll need to check out the following branch: 238_code_convention_refactoring
**Once you have added header comments let me know for which ones you have done so. This will help me keep track of what has been done or not.** 
Here is a list of functions which need header comments:
- [x] generateRawDataTable (AssetInfoController.java)
~- [ ] setCellValue (AssetInfoController.java)~
- [x] toAssetType (AssetTypeList.java)
- [x] getMeasurementsFromID (MeasurementDAO.java)
- [x] deleteMeasurementsFromID (MeasurementDAO.java)
- [x] insertMeasurement (MeasurementDAO.java)
- [x] setAssetUpdate (AssetDAOImpl.java)
- [x] getAssetTypeThreshold (AssetTypeDAOImpl.java)
- [x] insertAssetType (AssetTypeDAOImpl.java)
- [x] getAssetTypeList (AssetTypeDAOImpl.java)
- [x] getNameFromID (AssetTypeDAOImpl.java)
- [x] updateAssetType (AssetTypeDAOImpl.java)
- [x] deleteAssetTypeByID (AssetTypeDAOImpl.java)
- [x] getLastXMeasurementsByAssetIDAndAttributeID (AttributeDAOImpl.java)
- [x] nonParamQuery (DAO.java)
- [x] reduceData (DataPreProcessorController.java)
- [x] minimallyReduceData (DataPreProcessorController.java)
- [x] setContains (DataPreProcessorImpl.java)
- [x] getRemovedIndexList (DataPreProcessorImpl.java)
