### ISSUE TITLE
General enhancements - Code coverage tool

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#241]
As a developer, I want to be able to get accurate and complete code coverage provided by my unit tests.

Description:
The current code coverage reports provided by Clover seem to only be showing the statement code coverage. However, branch and method coverage are also needed.

Acceptance critieria:
- [ ] Have code coverage reports that include statement/line, branch and function coverage

**Comment by JayChouteau** [comment]
After reviewing, Clover does indeed provide coverage not only using statement coverage but using statement, function, and branch coverage. So we can keep using Clover, it does what we need it to do. Here is how CLover calculates the code coverage:
![Clover-Coverage](https://user-images.githubusercontent.com/47158909/107150489-021f1100-692c-11eb-9c72-898293d30604.PNG)

@rdsaliba since Clover does what we need, we don't need to investigate other testing tools for code coverage. I'll be putting the issue in review, you can close it once you see this.

**Comment by rdsaliba** [comment]
Happy to see we won't need to do any extra effort on this issue... Thanks Jeremie.
