### ISSUE TITLE
BUG - LSTM trained models too big to be saved in the database

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#247]
**Describe the bug**
The models that are trained with the LSTM model cannot be saved into the database. The size of those trained models is too big for it to be saved in the _trained_model_ table as a _serialized_model_ BLOB object.

**To Reproduce**
1. Make sure the models are set to retrain '1' in the database
2. Make sure the application is using the LSTM model as the default model
3. Run the application
4. The error should happen then

**Expected behavior**
When using LSTM to train the models, the models should be saved in the database as a serialized object in the trained model table. That way, the trained models can be fetched and used to calculate an asset RUL.

**Screenshots**
![image](https://user-images.githubusercontent.com/47158909/107150656-dc463c00-692c-11eb-8d81-f72d2a54ae3b.png)

**Desktop (please complete the following information):**
 - OS: both Windows and Mac

**Comment by PaulMicu** [comment]
2 issues were found during the bug investigation
1 - after some unknown changes, the train model no longer works as intended
2 - the Classifier object created by the LSTM model is larger than 64k which is what the BLOB column can store

**Comment by PaulMicu** [comment]
both issues were fixed as described in the pr #254
