### ISSUE TITLE
UI Feature - Images

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#248]
As a user, I would like to see images for the assets that I have.

Description
On the asset information page, the user would like to have the image of that specific asset displayed among the other info. There is currently uncertainty as to whether or not adding images for assets can be done dynamically. The first part would be to explore the possibilities.

Acceptance Criteria:
- [x] There is an image of the asset on that asset information page
- [x] Display image in Thumbnail on Assets page
- [x] Allow user to select image on Add Asset page
- [ ] Allow user to edit image on Edit Asset page [REMOVED]
- [x] If the asset does not have an image, a default display will be shown instead
- [x] Only the minimum number of images need to be added

**Comment by rdsaliba** [comment]
![image.png](https://images.zenhubusercontent.com/5f5b90e88d247ac7ad2cf5c0/97ee1e25-13f1-449b-949b-271006576297)

**Comment by rdsaliba** [comment]
![image.png](https://images.zenhubusercontent.com/5f5b90e88d247ac7ad2cf5c0/a306fffc-c5fb-4664-872b-6ad4e75c8268)

**Comment by rdsaliba** [comment]
![image.png](https://images.zenhubusercontent.com/5f5b90e88d247ac7ad2cf5c0/edcc2546-a9a3-4c9b-b1db-556ca946722c)

**Comment by rdsaliba** [comment]
Please note: the acceptance criteria for edit image on the edit asset page is removed since the page doesn't exist yet.
