### ISSUE TITLE
[SPIKE] Research on data preprocessing

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#25]
Data Preprocessing - As a developer, I need to search for a solution to clean the data so we can extract the condition indicators

**Comment by rdsaliba** [comment]
If we don’t have quality data feeding into our model, the resulting RUL assessment will be useless. Data preprocessing is necessary to clean the data and convert it into a form from which we can extract condition indicators. 

Document the findings and solution

**Comment by PaulMicu** [comment]
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/edit-v2/28508291
