### ISSUE TITLE
Input Validation

### ISSUE THREAD

**Issue by najimgh** [rdsaliba/notorious-eng#252]
As a user, I want to have validation on all inputs submitted from a form so that it matches the logical expectations.

Description:
Currently, we have Strings and Doubles on the input form. We want to validate the following:

Asset Name:
- Length of 50
- Not Null
- Special Symbols - No Restrictions
- Type Validation - String

Asset Description:
- Length of 300
- Can be Null
- Special Symbols - No Restrictions
- Type Validation - String

Serial Number:
- Length of 20
- Not Null
- Special Symbols - Letters, Numbers, Dash(-)
- Type Validation - String

Manufacturer:
- Length of 20
- Can be Null
- Special Symbols - Letters, Number, Dash(-)
- Type Validation - String

Category:
- Length of 20
- Can be Null
- Special Symbols - Letters, Dash(-)
- Type Validation - String

Site:
- Length of 20
- Can be Null
- Special Symbols - Letters, Numbers, Dash(-)
- Type Validation - String

Location:
- Length of 20
- Can be Null
- Special Symbols - Letters, Numbers, Dash(-)
- Type Validation - String

Asset Type Name:
- Length of 50
- Not Null
- Special Symbols - No Restrictions
- Type Validation - String

Asset Type Description:
- Length of 300
- Can be Null
- Special Symbols - No Restrictions
- Type Validation - String

Thresholds:
- The value of the Thresholds need to follow this logic: Advisory > Caution > Warning > Failure
- Type Validation - Double
- Non-Negative Values
- Can be Null
- Ok does not have a value

Acceptance Criteria:
- [ ] Input field turns red when input is wrong
- [ ] The form does not submit if there is an error
- [ ] Clear explanation to the user as to why the input is wrong

**Comment by rdsaliba** [comment]
Hi @najimgh,

Here's the tutorial video I have mentioned during the meeting. It could give you and idea on how to implement the changes.
https://www.youtube.com/watch?v=cwJK_WpseKQ

**Comment by najimgh** [comment]
Need to fix styling of error messages displayed before putting the issue into review.
