### ISSUE TITLE
DOC R3 - Refactoring report

### ISSUE THREAD

**Issue by najimgh** [rdsaliba/notorious-eng#271]
Acceptance Criteria:
- [ ] Release 3 documentation for the Refactoring section

The release 3 document, as well as the release 3 template, are in the team's drive.

IMPORTANT NOTE:
For this section, to confirm the refactoring activities, please use the tool that the prof develop and showed us:
https://chrome.google.com/webstore/detail/refactoring-aware-commit/lnloiaibmonmmpnfibfjjlfcddoppmgd?hl=en

This tool allows identifying the different refactoring activities in a commit. You can use it to go through all the commits and identify the correct refactoring activities

Feedback from Release 2:
Refactoring activity [3.5/4 points] I think you are performing the refactoring actions over multiple commits, because in many cases I checked for Extracting a class, only new code appeared in the commit. So, it is not clear where exactly the code was extracted from. Overall, you did significant refactoring activity.

**Comment by JayChouteau** [comment]
@Shirwarsame You need to linnk up the commits to the gitHub repo. As of now, you can't click on the link provided in your refactoring table.

**Comment by JayChouteau** [comment]
@Shirwarsame I left 2 comments in the release documentation for the refactoring part. Please check them out.

**Comment by JayChouteau** [comment]
@Shirwarsame I removed one pull request (184) because it was from sprint 6. Nice job on adding the other refactoring issues.

**Comment by JayChouteau** [comment]
Reviewed
