### ISSUE TITLE
UI Feature - Loading feedback/Notifications on background operations

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#277]
As a user, I would like to get feedback from the application on the operations performed and user actions.

Description:
This issue is part of the user story to give more UI feedback to the user on the operations he performs in the application. This task specifically targets having loading displays on the UI when the app performs operations in the background, especially when those tasks freeze, stagger or slow down the application.

Acceptance Criteria:
- [x] Mock-ups have been created and approved by the team
- [x] Mock-ups have been updated on Confluence
- [x] Method agreed for the loading feedback and notifications on background operations or confirmation dialogs
- [x] The loading UI feedback is to be used/needed for the following actions:
- [ ] ~~Saving Asset and Asset Type~~
- [ ] ~~Deleting an asset~~
  - [x] Deleting an asset type
  - [x] Generating trained models for a specific asset type on the asset type information page - model tab
  - [x] Add Fade In Fade Out transition when moving from one screen to another.

**Comment by PaulMicu** [comment]
I'm taking over this issue
