### ISSUE TITLE
Transfer Database to Online Service

### ISSUE THREAD

**Issue by jeffbuonamici** [rdsaliba/notorious-eng#290]
As a developer, I want the database to be available online so that it so uniform for all developers working on the project.

Acceptance Criteria:
- [x] Set up an account on an online cloud platform
- [x] Set up MariaDB server
- [x] Upload the latest dumpfile
- [x] Updating the config property files for the connection

**Comment by Shirwarsame** [comment]
Solved:
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/585531393/Database+Setup
