### ISSUE TITLE
F8 - The system shall display the selected RUL model parameters

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#311]
F8 - The system shall display the selected RUL model parameters

Acceptance Criteria:
On the asset type information screen, in the model tab:
- [x] selecting a model shows the associated model parameters for that model
- [x] all models have and display different parameters specific to that model
- [x] selecting a model will display the current parameter values associated with that model for that specific asset type
- [x] The parameter values displayed for an asset type are applied only to the currently selected asset type

**Comment by jfstamand** [comment]
Approved
