### ISSUE TITLE
F9 - The system shall provide the ability to edit a selected model RUL parameters

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#312]
F9 - The system shall provide the ability to edit a selected model RUL parameters

Acceptance Criteria:
On the asset type information screen, in the model tab:
- [x] all parameters of an RUL model can be edited and saved
- [x] The values can be brought back to the default values
- [x] The values can be reset to the previous values
- [x] Once new parameters values are saved, the trained model is updated and all assets are re-evaluated (for RUL value)

**Comment by jfstamand** [comment]
Approved
