### ISSUE TITLE
F10 - The system shall display a selected RUL model performance (prediction vs actual)

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#313]
F10 - The system shall display a selected RUL model performance (prediction vs actual)

Acceptance Criteria:
- [x] When clicking on "evaluate all", the system will display each model performance for the currently selected specific asset type
- [x] When clicking on "evaluate", the system will display that specific model's performance for the currently selected asset type 
- [x] The model performance will be shown as the RMSE of the model
- [x] The training and testing assets used for performance evaluation are selected by the user
- [x] The training and testing assets used for performance evaluation are all archived assets of the currently selected asset type

**Comment by jfstamand** [comment]
Approved
