### ISSUE TITLE
E1 - "Friendly" Interface

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#322]
E1 - The system shall have a “friendly” interface with the user

Acceptance Criteria:
- [x] The UI should have a distinct color palette that applies to different UI Components (such as buttons)
- [x] The UI should have icons for different UI components, namely buttons and menu options
- [x] The UI should have consistent UI components, including disposition and styling
- [x] The differentiation between Labels and text fields should be clear
- [x] There should be a clear differentiation between UI elements
- [x] Functionalities are intuitive and easy to do based on the UI
- [x] Titles and labels give a clear indication of the current screen
- [x] There is user input validation for any user input in the application
- [x] There is constant feedback of to the user of what is happening in the application

**Comment by jfstamand** [comment]
Approved
