### ISSUE TITLE
Add sidebar menu 

### ISSUE THREAD

**Issue by PaulMicu** [rdsaliba/notorious-eng#36]
As a User, I want to be able to navigate the system and the model pages on the application.

Notes: 
Create the following buttons on the left side as shown in the UI Prototype: https://notorious-eng.atlassian.net/l/c/mK3GJF0u
- Systemes 
- Models

the buttons should bring you to the selected page

The sidebar should be mobile friendly 

Acceptance criteria:
- [ ] System button brings you to the system dashboard page
- [ ] Model button brings you to the model dashboard page

**Comment by jeffbuonamici** [comment]
Version 0.6 is currently the latest prototype version:
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/87392587/v0.6
