### ISSUE TITLE
System information view

### ISSUE THREAD

**Issue by PaulMicu** [rdsaliba/notorious-eng#37]
As a User, I want to be able to view all the current systems and their status

Notes: 
replicate UI Prototype: https://notorious-eng.atlassian.net/l/c/x3XnFAFK

notes: 
Needs to be resizable friendly

**Comment by jeffbuonamici** [comment]
Version 0.6 is currently the latest prototype version:
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/87392587/v0.6
