### ISSUE TITLE
Remove an asset through the UI

### ISSUE THREAD

**Issue by jeffbuonamici** [rdsaliba/notorious-eng#41]
As a User, I want to delete an asset from the system so that it is removed from the monitored list.

Refer to UI Prototypes: https://notorious-eng.atlassian.net/l/c/Y5Fr7SZ5

Acceptance Criteria:
- [x] Take the input from the UI and remove the asset from the DB
- [x] Prompts the user with a message "Are you sure you want to permanently delete this item?" before deletion
- [x] Make sure the systems view page is refreshed (asset is deleted from the page - UI)

**Comment by Shirwarsame** [comment]
SQL script must first be finalized and foreign keys referencing asset_id must contain ON DELETE CASCADE

**Comment by rdsaliba** [comment]
Hi @Shirwarsame 
I have updated the acceptance criteria. Please take a look :)
