### ISSUE TITLE
Display Selected System Information

### ISSUE THREAD

**Issue by Khal-Shah** [rdsaliba/notorious-eng#44]
As a user, I want to view the detailed system information for the system that I selected.

Acceptance Criteria (the following items should be displayed):
- [ ] RUL
- [ ] Sensor information
- [ ] RUL model
- [ ] System Type
- [ ] System Name
- [ ] System Serial Number
- [ ] System Description
- [ ] Manufacturer
- [ ] Site Location
- [ ] Add(Or Select) Model Button

**Comment by jeffbuonamici** [comment]
Make sure it follows current UI Prototype:

https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/24379414/UI+Prototypes

**Comment by jeffbuonamici** [comment]
Version 0.6 is currently the latest update:
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/87392587/v0.6
