### ISSUE TITLE
Display System Dashboard Details (Thumbnail View)

### ISSUE THREAD

**Issue by Shirwarsame** [rdsaliba/notorious-eng#46]
As a user I want to see main system details for all systems.

Acceptance Criteria:
- [ ] System Type
- [ ] Serial Number
- [ ] RUL
- [ ] RUL Model
- [ ] System Health (Dummy data)

**Comment by jeffbuonamici** [comment]
Make sure it follows current UI Prototype:

https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/24379414/UI+Prototypes

**Comment by jeffbuonamici** [comment]
Version 0.6 is currently the latest update:
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/87392587/v0.6
