### ISSUE TITLE
[SPIKE] Modern UI

### ISSUE THREAD

**Issue by PaulMicu** [rdsaliba/notorious-eng#50]
As a dev, i want my application to be mobile friendly and look modern.

Have a sample running on javaFX with different solutions
ex: Bootstrap, JavaFX Web View

To be documented in Confluence

**Comment by najimgh** [comment]
Documentation to set-up JavaFX : [https://openjfx.io/openjfx-docs/#introduction]

**Comment by jeffbuonamici** [comment]
This is what I was able to come up with in terms of responsive JavaFX UI. The only issue is that JavaFX doesn't have good functionality for different display sizes. 

![Responsive.PNG](https://images.zenhubusercontent.com/5f5b96995e1da195741dab57/77abc37f-f1fb-4762-87e8-789a85fe2598)
