### ISSUE TITLE
Setup Database

### ISSUE THREAD

**Issue by PaulMicu** [rdsaliba/notorious-eng#51]
As a dev, I need a place to store all the system and sensor information in a secure database.

Setup an internal database and connect it into the application.

Acceptance Criteria:
- [x] Setup internal database
- [x] Document which database is implemented and why

Notes;
H2, Derby, HSQLDB are possible solutions.

**Comment by Shirwarsame** [comment]
To pull the database container from docker :docker pull shirwarsame/lmdatabase 

TO run mysql: docker exec -it angry_bhaskara mysql -u root -p

password:123

**Comment by JayChouteau** [comment]
DBMS work session summary (all assignees present):
- H2, Derby, MariaDb, HyperSQL, MySQL all seem very similar and all connect to a Java application through JDBC
- blocking: is there any limitations to the pool of SQL DBMS we can choose from ?
- blocking: is there any limitation to using a NoSQL DMBS?

[DBMS comparator](https://db-engines.com/en/system/Derby%3BH2%3BHyperSQL%3BMariaDB%3BMySQL)

**Comment by najimgh** [comment]
- Able to test and connect a dummy java project to MySQL.
 - Will try and connect MySQL to the project

**Comment by PaulMicu** [comment]
As discussed in our meetings, MySQL will not work for our project we need an embedded database, MySQL is cannot be embedded into our java application, please choose one from the 3 mentioned in the ticket

**Comment by najimgh** [comment]
- Able to implement and test H2 as well as HSQLDB as an embedded in-memory database.

- H2 is preferred over HSQLDB due to its ease of implementation and better documentation.

- Documentation on both databases and why we chose H2 is on confluence

**Comment by Shirwarsame** [comment]
Link to documentation:
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/136249345/H2+or+HSQLDB+using+JDBC+API

**Comment by najimgh** [comment]
Changed to MariaDB as per Product owner's request
