### ISSUE TITLE
[SPIKE] Mimosa framework implementation

### ISSUE THREAD

**Issue by PaulMicu** [rdsaliba/notorious-eng#52]
As a dev, i want to implement the open system architecture for CBM

Reseach about the framework and validated if it could be used as the skeleton to the system to be.

**Comment by rdsaliba** [comment]
The OSA-CMB open system architecture developed by MIMOSA could be used as the skeleton to our system-to-be. It defines a generic architecture approach to predictive maintenance that must be adapted to the stakeholders need. One important aspect to note; the framework lacks indications as to the performance indicators, potential structural constraints or partial imposed solutions by stakeholder. We need to figure it out.

Please leave any comment on your findings or understanding.

@Shirwarsame @najimgh @t98b
