### ISSUE TITLE
Class diagrams

### ISSUE THREAD

**Issue by PaulMicu** [rdsaliba/notorious-eng#53]
As a dev, i want to create a class diagram to better understand the project architecture.

**Comment by rdsaliba** [comment]
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/95289442/Class+Diag+v0.1

To be reviewed and tuned.

**Comment by najimgh** [comment]
Added design pattern page on confluence and suggested patterns we could use.
