### ISSUE TITLE
Additional UI Prototypes

### ISSUE THREAD

**Issue by PaulMicu** [rdsaliba/notorious-eng#54]
parameters view (Clarify with the PO)
add RUL model view (Clarify with the PO)
System view (convert to tablet)

Sensor view
 - graph

System view
 - Rul 
 - Name 
 - System Type

System View in system
- all information from add system
 - all models used, 
 - RUL for each model

**Comment by PaulMicu** [comment]
Added Sensor view, System view(short), System View(detailed) and System page

Extra: Added an alternative color scheme with the LM logo

Confluence link: https://notorious-eng.atlassian.net/l/c/qJwYpjmb

**Comment by rdsaliba** [comment]
What is the status of this issue? @PaulMicu

**Comment by PaulMicu** [comment]
@rdsaliba No new pages to prototype at this moment and the feedback from the PO has been positive with no notes on anything to change. If you agree i will close this issue
