### ISSUE TITLE
Prepare Release 1 Document

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#56]
Start the documentation for the Release 1
Look at the template

**Comment by rdsaliba** [comment]
What is the status of this issue? @najimgh

**Comment by najimgh** [comment]
Will be prepared tonight @rdsaliba

**Comment by rdsaliba** [comment]
Hi @najimgh 
The document is missing the content for the following sections:
* project description
* Sprint 1 summary
* Sprint 1 retrospective 
* UI prototypes

**Comment by najimgh** [comment]
@rdsaliba 
The content mentioned above has been added along with Personas.
Description for the UI prototypes to be done
