### ISSUE TITLE
High-Level Architecture View

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#57]
As a dev, I want to produce a high level architecture view of the system so that we have an overview of the entire system to be developed.

Document in confluence

**Comment by JayChouteau** [comment]
A first incomplete draft was created for the component diagrams. I am leaving the link in this issue as well because I think it is part of the high-level architecture.
- [CD v0.1](https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/67633180/CD+v0.1)

**Comment by rdsaliba** [comment]
Hi @JayChouteau, I have complemented your work with some precisions on the architectural views.
I will be reviewing your diagrams as well.

Please take a look at the following proposed system:
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/83623937/Logical+Architecture
