### ISSUE TITLE
Weka Dependency and libraries

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#59]
As a dev, I want to integrate the Weka library to the system so that I can use its machine learning libraries in order to calculate the RUL.

Also, investigate on the useful libraries, leave trace of your findings here as comments.

Develop on the high level implementation we could do to calculate RUL.
Methodology, process.

Maybe SPLIT this story in 2...

**Comment by Khal-Shah** [comment]
Trace of findings left on confluence: CBMS > Data & Algo Research
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/74153985/Data+Algo+Research

We have a high level description and overview now, it will be continuously updated and refined there as our understanding of ML improves.

**Comment by rdsaliba** [comment]
Here is a comprehensive approach on using the CMAPPS Dataset
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/83755028/CMAPPS+Dataset

**Comment by rdsaliba** [comment]
@Khal-Shah Will you be able to prepare a demo for the meeting this Thursday?
