### ISSUE TITLE
DOC R3 - Testing Report

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#61]
Acceptance Criteria:

- [x] Release 3 documentation for the Testing section

Make sure all sections are updated:
- [x] Unit testing
- [x] Test code coverage
- [x] Acceptance testing (Jeremie)
- [x] System Tests (Khaled)

The release 3 document, as well as the release 3 template, are in the team's drive.

Feedback from release 2:
Unit/System Testing Report [2/3 points] 66 unit tests added in the server and 33 in the UI. This is a significant increase given the complete lack of unit tests in the first release. The code coverage is 63% in the UI and 33.8% in the server. 5 acceptance tests were signed-off by the PO. The research on system testing tools in not detailed. System tests could not be fully automated due to performance issues (some tests were taking too much time to finish for some team members).

**Comment by JayChouteau** [comment]
@Khal-Shah I left some comments for the system testing part. Also, we are missing a video for F5. Other than that, super excellent work on the system testing btw!! Big job and it looks neat.

**Comment by Khal-Shah** [comment]
Thank you @JayChouteau 

As for F5 (The system might suggest maintenance actions/recommendations to the user) wasn't part of the system testing issue: https://app.zenhub.com/workspaces/notorious-eng-5f5b91b10156a900162c5640/issues/rdsaliba/notorious-eng/164

I think when going over the features and defining the acceptance criteria for system testing, we determined it wasn't testable or redundant with the other tests.

If you have a test suggestion, I could try to write a quick test and record it without making any PR.

**Comment by JayChouteau** [comment]
> Thank you @JayChouteau
> 
> As for F5 (The system might suggest maintenance actions/recommendations to the user) wasn't part of the system testing issue: https://app.zenhub.com/workspaces/notorious-eng-5f5b91b10156a900162c5640/issues/rdsaliba/notorious-eng/164
> 
> I think when going over the features and defining the acceptance criteria for system testing, we determined it wasn't testable or redundant with the other tests.
> 
> If you have a test suggestion, I could try to write a quick test and record it without making any PR.

@Khal-Shah I still think we could have a quick system test even if it is redundant, just to be safe. For the test case scenario, you can use the acceptance criteria of this issue (i'd say the first 3):
https://github.com/rdsaliba/notorious-eng/issues/203

Let me know if that makes sense to you and if you add it
