### ISSUE TITLE
Database Design Diagram

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#62]
As a dev, I want to design the structure of my database so that we have an idea of the relationships between all entities of the system.

Acceptance Criteria:
- [x] Design Database to accept datasets.
- [ ] Database should be in Third Normal Form

**Comment by JayChouteau** [comment]
The proposal for the database design can be seen on the [database Design Confluence page](https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/128516116/Database+Design)

**Comment by JayChouteau** [comment]
One question when it comes to database design:
- are we loading multiple datasets at once into our database or are we looking at only one dataset every time we run the program? Depending on the answer, we will have to add an attribute to tag which dataset the info belongs to.

**Comment by PaulMicu** [comment]
The design requires more refinement, this is not modular enough to be able to be used by any datasets. The design is also not in 3N.
A few points that need to be addressed: 
- We need a table for the dataset, this table will help us identify between systems of different datasets and between training and live data ( it will have 8 entries for our needs)
- We need a table to contain the operational conditions on the datasets, another table will link between this table and the dataset table for each conditional setting of the dataset (it should have 4 entries, Conditions: ONE, Conditions: SIX, Fault Modes: ONE and Fault Modes: TWO )
- The System_RUL table needs to be made more modular, this can be done by having another table that contains the model info (2 entries) . then the System_RUL can be renamed to something like RUL_Mesurements, and link it through a relationship table to the system measurements table
- The sensor table should share a relationship table with the System measurements table. this table will contain the measurements of each sensor for the specified time cycle and system.
- The system measurement table should not contain a list of the sensors, it should only contain a reference to the system and a time cycle, the sensor/operational setting 


There might be more to do but this would be a good start.

**Comment by JayChouteau** [comment]
The database design was modified and some comments were added on the [confluence page](https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/128516116/Database+Design).

**Comment by JayChouteau** [comment]
The database design was modified (ER + relational schema) to better reflect the implementation. See [confluence page](https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/128516116/Database+Design)

**Comment by rdsaliba** [comment]
Yes this better reflects the system's need. I reviewed the diagram and it captures the requested modifications.
