### ISSUE TITLE
DOC R3 - UI

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#63]
Acceptance Criteria:

- [ ] Release 3 documentation for the UI Design section
- [ ] Mockups
- [ ] Make sure that screen mockups are correctly linked to user stories.

The release 3 document, as well as the release 3 template, are in the team's drive.

IMPORTANT NOTE:
- This section needs to be updated with our current application UI. HOWEVER, the professor will not go over in details or ask questions about this section, it doesn't need to be exhaustive.

Release 2 feedback:
None

**Comment by PaulMicu** [comment]
this has been pushed back by the PO with Docker as non-essential

**Comment by JayChouteau** [comment]
@najimgh it seems that the UI mock-ups 2.0 are not up to date with our latest UI version. Could you do a 2.1 that is updated with the latest changes to our app?

**Comment by JayChouteau** [comment]
@najimgh I left a comment for the UI in the doc basically saying we can remove all the old UI images from releases 1 and 2 since the current updated version is more relevant for this section. You can let me know what you think

**Comment by najimgh** [comment]
@JayChouteau I didn't have the adobe xd files to make a v2.1 so I took screenshots of the app instead since the deadline is coming up. I have also removed the old UI images from releases 1 and 2 (including the prototypes) as per your suggestion. Removing those old UI images makes the UI section more clear and less cluttered.

**Comment by JayChouteau** [comment]
@najimgh The adobe xd files were on the drive. However, screenshots will be sufficient. Honestly, it looks good. 1 comment: Could you add the add asset type screen/view on both the release report and the confluence? You can close the issue once that is done

**Comment by najimgh** [comment]
Done
