### ISSUE TITLE
Display System Dashboard Details (List View)

### ISSUE THREAD

**Issue by jeffbuonamici** [rdsaliba/notorious-eng#66]
As a user, I want to visualize the systems in a list view so that it's easier to navigate through the assets.

This user story will be realized by creating a second view of the system dashboard. A list view of all the systems with their details will be created as the second view of the system dashboard. The first view of the system dashboard is the more general grid view.

Acceptance Criteria:
- [x] Display a list of all systems as the "System Dashboard Details" View
- [x] Display System Type
- [x] Display Serial Number
- [x] Display RUL Value
- [ ] Display RUL Model
- [ ] Display System Recommendation

**Comment by jeffbuonamici** [comment]
Make sure it follows current UI Prototype:

https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/24379414/UI+Prototypes

**Comment by jeffbuonamici** [comment]
Version 0.6 is currently the latest prototype version:
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/87392587/v0.6

View a list of all versions here:
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/24379414/UI+Prototypes

**Comment by jeffbuonamici** [comment]
We currently don't have a System Recommendation to display.

**Comment by JayChouteau** [comment]
@jeffbuonamici I reviewed the PR attached to this issue (#117 ) and left some comments and review in there. Accepted overall. The only thing I mentioned was maybe a change in the tab styling for a future improvement.
