### ISSUE TITLE
Remove Scroll bar and add touch capable scrolling 

### ISSUE THREAD

**Issue by PaulMicu** [rdsaliba/notorious-eng#68]
As a user, I want to scroll using touch gesture so that a user could use his finger to scroll up and down.

Acceptance criteria:
- [x] Remove scroll bars from all pages
- [x] Allow scrolling by dragging the screen, as it would be on a tablet

**Comment by jeffbuonamici** [comment]
Version 0.6 is currently the latest prototype version:
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/87392587/v0.6

View a list of all versions here:
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/24379414/UI+Prototypes

**Comment by PaulMicu** [comment]
@jeffbuonamici  where is the PR for review?

**Comment by jeffbuonamici** [comment]
@PaulMicu Yeah sorry it was on a branch with another issue.

**Comment by JayChouteau** [comment]
@jeffbuonamici We will close the issue for now for sprint purposes and will get a tablet for the next sprint to test certain features out. I made some reviews and comments on the related PR (#117 )
