### ISSUE TITLE
Add Quality Measurements

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#81]
At the end of each Sprint record the value for each of the following metrics:
size, duplication, documentation, complexity, coupling, cohesion, technical debt, security vulnerabilities, and code convention violations.
You should take actions in each Sprint to improve these metrics. List the commits and pull requests in which technical debt, security vulnerabilities, and code convention violations have been addressed. Link to your Refactoring report actions taken to improve complexity, duplication, coupling, cohesion, readability and other design/code quality metrics. 
Finally, create a chart showing the evolution of each metric over the Sprints.

**Comment by rdsaliba** [comment]
At the end of each Sprint record the value for each of the following metrics:
size, duplication, documentation, complexity, coupling, cohesion, technical debt, security vulnerabilities, and code convention violations.
You should take actions in each Sprint to improve these metrics. List the commits and pull requests in which technical debt, security vulnerabilities, and code convention violations have been addressed. Link to your Refactoring report actions taken to improve complexity, duplication, coupling, cohesion, readability and other design/code quality metrics. 
Finally, create a chart showing the evolution of each metric over the Sprints.

**Comment by JayChouteau** [comment]
Added some explanation on our SonarQube numbers
