### ISSUE TITLE
DOC R3 - Architecture

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#86]
Acceptance Criteria:

- [x] Release 3 documentation for the Architecture section
The release 3 document, as well as the release 3 template, are in the team's drive.

Make sure all sections are updated:
- [x]  Overview (Jeremie)
- [x]  Domain model (Jeremie)
- [x]  Component Diagram (Talal)
- [x]  ER Diagram (Jeremie)
- [x]  Class Diagram (Najim)
- [x]  Design patterns (Najim)
- [x]  External libraries (Khaled, Najim)
- [x]  Experimental design (Khaled)

IMPORTANT NOTE:
- This section needs to be updated with our current application architecture. HOWEVER, the professor will not go over in details or ask questions about this section, it doesn't need to be exhaustive

Release 2 feedback:
Software Architecture [2/2 points] The class diagrams are now generated from source code (seems like ObjectAid UML). Five design patterns are discussed regarding their extension points and fit for the project requirements. Some are already implemented, while others are planned for future implementation. The Data Access and Module pattern were added in Release #2, but Observer was discarded.

**Comment by JayChouteau** [comment]
See issue #45

**Comment by JayChouteau** [comment]
@Khal-Shah @najimgh I consider External Libraries and Design patterns done since we didn't add any.

**Comment by JayChouteau** [comment]
@Khal-Shah Nice doc on experimental design, I reviewed it and it's good!

**Comment by Khal-Shah** [comment]
@JayChouteau, perhaps @Shirwarsame's cloud DB issue be touched on in external libraries? If not there then maybe in the ER diagram part where DB is more relevant. Either way, I think we should write a few sentence about it.

**Comment by JayChouteau** [comment]
> @JayChouteau, perhaps @Shirwarsame's cloud DB issue be touched on in external libraries? If not there then maybe in the ER diagram part where DB is more relevant. Either way, I think we should write a few sentence about it.

I don't think we really need it since we added it only at the end of sprint 9 and that lockheed Martin won't use it.
