### ISSUE TITLE
(F13) Ascending/Descending asset list by RUL

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#87]
As a user, I want to filter the assets page by RUL value so that the list is displayed in either ascending or descending order.

Acceptance Criteria:
- [x] Add a filter button that links to the RUL values
- [ ] Update Mock-up with a new version on Confluence to reflect this change (link in the issue)
- [x] Filter Asset-grid view by ascending/descending RUL
- [x] Filter Asset-list view by ascending/descending RUL

**Comment by JayChouteau** [comment]
@najimgh Since the button isn't existing yet, you will have to create the button and also update the mock-up on Confluence/GitHub by creating a new version. Don't hesitate to reach out to @jeffbuonamici for help on this.

**Comment by JayChouteau** [comment]
@najimgh Since the acceptance criteria include both the asset dashboard grid and list view, you will need the creation of the list view to be done to complete this user story (#66). Once again, you can check that out with Jeff.

**Comment by jeffbuonamici** [comment]
This has been done for the list view. I completed this in issue #66.

**Comment by JayChouteau** [comment]
@jeffbuonamici , you said that this was done. Are all of the acceptance criteria covered. If so, could you check them? @najimgh you might be able to help provide some light on this as well.

**Comment by najimgh** [comment]
Need to change how this feature is implemented due to the data being pulled in real-time
