### ISSUE TITLE
Establish a system type threshold boundaries for RUL values

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#89]
As a user, I want to establish the threshold boundaries for system type recommendations.

Acceptance Criteria:
- [x] User can define the threshold values of each recommendation boundary for a specific asset type (through UI)
- [x] The thresholds are expressed as integer (RUL)
- [x] The threshold values for an asset type are stored in the database
- [ ] Unit tests
- [x] The threshold names/recommendation labels are fixed by the application

Boundary values are defined for a specific system type and can be updated by the user. A table needs to be added to the database for this.

PO precision (16-11-2020):
The RUL value thresholds for different maintenance recommendations such as good, to be repaired, or to be replaced are determined by the user. These values are saved in the database and compared to a specific asset RUL value to establish the displayed recommendation for that asset.

**Comment by JayChouteau** [comment]
Need confirmation with the PO as to which recommendation labels he is looking for (the list of recommendation labels)
