### ISSUE TITLE
Model Serialization

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#90]
As a dev, I want the classifier object to be calculated only once and persisted in the DB so that it can be accessed for future use.

Acceptance Criteria:
- [x] The classifier object is serialized
- The path to serialized objects is saved in the database in the trained model table
- The path is associated with the corresponding system type

Description
The database currently has a table for trained models. The goal is to serialized this classifier object (trained model for that system type) so it can be de-serialized and access for future uses instead of being recalculated every time. The trained model table holds the path to the serialized object as an attribute.

**Comment by PaulMicu** [comment]
a little change to the acceptance criteria, the object itself will be saved in the database not the path, this will ensure that all instances of the application are using the exact same Classifier
