### ISSUE TITLE
BUG - Database connection object being created without ever being closed

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#93]
This bug is an issue that was found by SonarQube. 

### Description
In the **database** class, on line 42, the connection object to the database is created without ever being closed, which could lead to leaks, misbehaviors of failures. 

### Solution
The solution is to close the connection object right after the operations were performed.

**Comment by JayChouteau** [comment]
@najimgh @rdsaliba Just letting you know that this issue is linked to the #101 (SonarQube - Refactoring) since this bug was noted by SonarQube. Just making sure you guys stay in touch to not do double the work and keep each other updated.

**Comment by najimgh** [comment]
Solution: The bug has been fixed by adding a function that stops the connection object.

**Comment by JayChouteau** [comment]
Pull request was approved with some minor modifications.
