### ISSUE TITLE
Prognostic Assessment using Linear Regression (F4)

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#96]
F4 - The system shall determine the remaining useful life using different models.

As a user, I want to calculate the remaining useful life of engine using the linear regression model

Acceptance Criteria:
- [x] The system displays what model is used for the prognostic assessment
- [x] The system displays the calculated RUL for every system.

**Comment by jfstamand** [comment]
Your acceptance criterias seems ambiguous to me.
The accceptance criteria should define the boundaries of a user story, and are used to confirm when a story is completed and working as intended.

**Comment by rdsaliba** [comment]
Hi @jfstamand

The acceptance criteria have been modified based on your comment. Please refer to section 4.8 and 6.1 of our documentation for a complete description of the applied methodology. Let us know if this meet the expectations as we need your sign off on this user story. In this case, it would be a partial sign off since there is still one model to implement. Awaiting your feedback.

**Comment by jfstamand** [comment]
Acceptance criterias approved
