### ISSUE TITLE
Research - Model Parameters (LSTM)

### ISSUE THREAD

**Issue by JayChouteau** [rdsaliba/notorious-eng#97]
As a user, I would like to change the value of certain LSTM model parameters to tune the model if it is possible.

Acceptance criteria:
- [x] Research on the possibility of editing parameters that are input in the RUL LSTM model
- [x] Assess the impact of such changes on the model calculation and the limitations of it
- [x] Document on Confluence

 Description:
The PO added this requirement with the idea in mind that certain parameters used in the RUL calculation with RUL models could be modified to tune the RUL values. He thought it would be interesting for the user to edit the values of those parameters to see the influence on the model calculation. In this particular case, it would be to check if the LSTMpossesses any parameter as an input that could be tuned within a certain range by a user. An impact assessment of such modification should be performed as well.

**Comment by Khal-Shah** [comment]
Confluence document:
https://notorious-eng.atlassian.net/l/c/kQPfvaS8
